spring:
  datasource:
    url: jdbc:h2:mem:guoguo_blog_test;MODE=MySQL;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false

app:
  jwt:
    secret: ${JWT_SECRET:ZG9uJ3QtdXNlLXRoaXMtaW4tcHJvZC0zMi1ieXRlLXNlY3JldA==}
    access-token-expiration-ms: 3600000
    refresh-token-expiration-ms: 604800000
